language: generic
sudo: required
services:
  - docker
  
before_install:
  - docker build -t nicoleow/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true nicoleow/docker-react npm run test -- --coverage

deploy:
  provider: elasticbeanstalk
  region: "ap-southeast-2"
  app: "docker-react"
  env: "Docker-react-env"
  bucket_name: "elasticbeanstalk-ap-southeast-2-921450268289"
  bucket_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: 
    secure: "$AWS_SECRET_KEY"



  Docker-react-env.qteadfsasf.ap-southeast-2.elasticbeanstalk.com


access_key_id: $AWS_ACCESS_KEY
secret_access_key: $AWS_SECRET_KEY